python scripts/txt2img.py \
    --prompt "red cracked bricks" \
    --outdir "outputs/wo_pattern_text" \
    --ckpt logs/2023-02-20T23-25-07_ae/checkpoints/last.ckpt \
    --H 512 --W 512 \
    --n_samples 1 \
    --ddim_steps 25 \
    --seed 42 \
    --dpm_solver \
    --config configs/stable-diffusion/material.yaml \
    --scale 5.0 \
    --device_num 1 \