model:
  base_learning_rate: 1.0e-4
  target: ldm.models.pbr_autoencoder.PBRAutoEncoder
  params:
    embed_dim: 4
    monitor: train/rec_loss

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: ldm.modules.losses.PBRDecoderLoss
      params:
        perceptual_weight: 1.0

    # scheduler_config: # 10000 warmup steps
    #   target: ldm.lr_scheduler.LambdaLinearScheduler
    #   params:
    #     warm_up_steps: [ 1 ] # NOTE for resuming. use 10000 if starting from scratch
    #     cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
    #     f_start: [ 1.e-6 ]
    #     f_max: [ 1. ]
    #     f_min: [ 1. ]

data:
  target: train_pbr.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 12
    num_val_workers: 0 # Avoid a weird val dataloader issue
    train:
      target: ldm.data.simple.PBRMap
      params:
        data_dir: /root/hz/DataSet/mat
        pbr_type: normal
        mode: train
        # image_transforms:
        # # - target: torchvision.transforms.Resize
        # #   params:
        # #     size: 512
        # #     interpolation: 3
        # # - target: torchvision.transforms.RandomCrop
        # #   params:
        # #     size: 512
        # - target: torchvision.transforms.RandomResizedCrop
        #   params:
        #     size: 512
        #     scale: [0.8, 1.0]
        # - target: torchvision.transforms.RandomVerticalFlip
        # - target: torchvision.transforms.RandomHorizontalFlip
    validation:
      target: ldm.data.simple.PBRMap
      params:
        data_dir: /root/hz/DataSet/mat
        mode: test
        pbr_type: normal


lightning:
  find_unused_parameters: False

  modelcheckpoint:
    params:
      every_n_train_steps: 1500
      save_top_k: -1
      monitor: NULL

  callbacks:
    image_logger:
      target: train_pbr.ImageLogger
      params:
        batch_frequency: 200
        max_images: 4
        increase_log_steps: False
        log_first_step: True
        log_all_val: True

  trainer:
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1